/**
 * Wire-level event protocol between providers and the agent loop / TUI.
 *
 * Every event a provider emits — whether scripted by `MockProvider` (M2) or
 * generated by a real model like Anthropic (M5+) — is one of these variants.
 * The TUI consumes the same stream and renders accordingly.
 *
 * Variants are tagged by `type` (a string literal) so TypeScript narrows
 * inside `switch (event.type)` or `if (event.type === ...)` — every branch
 * sees only the fields that exist on that variant.
 *
 * @see docs/TUI-DESIGN.md §10 for the canonical contract and rendering rules.
 */
export type StreamEvent =
  /**
   * A chunk of streamed assistant text. Many `text_delta` events concatenate
   * into a single assistant message. Emitted as the model produces tokens.
   */
  | {
      type: 'text_delta';
      delta: string;
    }
  /**
   * The model has decided to call a tool. Emitted once per call when the
   * complete tool block has assembled. `id` is unique per call and ties this
   * event to its corresponding `tool_use_running` and `tool_use_end` events.
   */
  | {
      type: 'tool_use_start';
      id: string;
      name: string;
      input: Record<string, unknown>;
    }
  /**
   * Optional progress update while a tool is running. Tools like `bash` may
   * stream partial stdout this way. Emitted zero or more times between
   * `tool_use_start` and `tool_use_end` for the same `id`.
   */
  | {
      type: 'tool_use_running';
      id: string;
      partialOutput?: string;
    }
  /**
   * The tool has finished executing. `result` is what the model sees in its
   * next turn; `isError` is what the TUI uses to render in success vs danger
   * color (see TUI-DESIGN.md §4.5 vs §4.12).
   */
  | {
      type: 'tool_use_end';
      id: string;
      result: TextContent[];
      isError: boolean;
    }
  /**
   * The agent is asking the user to approve a tool call. The TUI renders an
   * inline prompt (§4.7) and waits for a single-key answer. `patterns` is
   * the list of allow-rule patterns that "yes, always" would persist for the
   * session.
   */
  | {
      type: 'permission_ask';
      id: string;
      prompt: string;
      patterns: string[];
    }
  /**
   * Updates the activity line above the input box (§4.3).
   * - `"thinking"` while the model is generating without a tool.
   * - A tool name string while a tool is running.
   * - `null` when idle.
   */
  | {
      type: 'status_change';
      active: string | null;
    }
  /**
   * Something went wrong while streaming. `recoverable: true` means the TUI
   * may offer a retry (§4.11); `false` is a terminal failure. An `error`
   * event is always followed by a `stop` event (with `reason: "error"` if
   * unrecoverable).
   */
  | {
      type: 'error';
      message: string;
      recoverable: boolean;
    }
  /**
   * Terminal event — always the last thing in the stream.
   * - `finished` is the happy path.
   * - `aborted` means the user pressed Esc / Ctrl-C.
   * - `error` follows an unrecoverable `error` event.
   * - `length` means the model hit its output token cap.
   */
  | {
      type: 'stop';
      reason: 'finished' | 'aborted' | 'error' | 'length';
    }
  /**
   * Compaction has begun. The TUI shows a `⋯ compacting` indicator in the
   * status bar (§4.14) until the corresponding `compact_end`. `tokensBefore`
   * is the conversation's token count entering compaction.
   */
  | {
      type: 'compact_start';
      tokensBefore: number;
    }
  /**
   * Compaction has finished; the conversation history has been summarized.
   * `tokensAfter` is the new token count. The TUI clears the indicator.
   */
  | {
      type: 'compact_end';
      tokensAfter: number;
    };

/**
 * A text content block. Used inside `tool_use_end.result` (and later as a
 * component of assistant messages once conversation state is modeled in M6).
 *
 * Matches Anthropic's content-block shape so the M5 provider can pass these
 * through without translation.
 */
export type TextContent = {
  type: 'text';
  text: string;
};

/**
 * Stub for image content blocks. The real shape (base64 vs URL, mime type,
 * etc.) is deferred to M5 — once we know exactly how Anthropic returns
 * images we'll pin the field set down. Until then this is a discriminant
 * placeholder so `TextContent | ImageContent` unions compile.
 */
export type ImageContent = {
  type: 'image';
  // TODO: payload deferred - see M5
};

/**
 * Top-level shape of a scenario JSON file consumed by `MockProvider`.
 *
 * Scenarios script a `StreamEvent` sequence with timing — used both as demo
 * material (drive `cog --mock <path>`) and later as test fixtures for the
 * TUI (M3+).
 *
 * @see packages/providers/scenarios/README.md for the format docs and
 * canonical scenario list.
 */
export type ScenarioFile = {
  /** Short identifier — usually matches the filename without `.json`. */
  name: string;
  /** One-line summary of what this scenario exercises. */
  description: string;
  /** Ordered list of events the mock will emit, with optional inter-event delays. */
  events: ScenarioEvent[];
};

/**
 * One event in a scenario file. Identical shape to `StreamEvent` plus an
 * optional `delayMs` that tells the mock how long to wait **before** emitting
 * it. The mock strips `delayMs` before yielding so the agent loop / TUI only
 * see `StreamEvent`s.
 */
export type ScenarioEvent = StreamEvent & { delayMs?: number };

/**
 * The contract every LLM provider implements. v1 has `MockProvider` (M2);
 * M5 adds `AnthropicProvider`; future providers (OpenAI-compatible, etc.)
 * plug in behind the same surface.
 *
 * Providers must never throw or return rejected promises for request /
 * model / runtime failures — failures must be encoded as `error` events
 * in the returned stream, followed by a terminal `stop` event with
 * `reason: "error"`. The agent loop relies on this contract to stay linear
 * (no try/catch wrapping the for-await).
 *
 * @see docs/RESEARCH.md §4 for the streaming contract rationale (from pi).
 */
export interface Provider {
  stream(input: ProviderInput): AsyncIterable<StreamEvent>;
}

/**
 * Everything a provider needs to produce its next response.
 *
 * `messages` and `tools` are intentionally `unknown[]` for M2 — the mock
 * ignores them, and the real shapes will be defined in M6 (agent loop +
 * tools) when conversation state and tool specs become concrete.
 */
export type ProviderInput = {
  /** Conversation history. Shape tightens in M6 once messages are modeled. */
  messages: unknown[];
  /** Tool schemas the model may call. Shape tightens in M6 with the tool registry. */
  tools?: unknown[];
  /** Model id, e.g. `"claude-haiku-4-5"` or `"mock"`. */
  model: string;
  /**
   * Cancellation signal. Providers must honor this — on abort, emit a
   * terminal `stop` event with `reason: "aborted"` and return.
   */
  signal?: AbortSignal;
};
